-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 23:25:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema torneoTenisMesa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `torneoTenisMesa` ;

-- -----------------------------------------------------
-- Schema torneoTenisMesa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `torneoTenisMesa` DEFAULT CHARACTER SET utf8 ;
USE `torneoTenisMesa` ;

-- -----------------------------------------------------
-- Table `torneoTenisMesa`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `torneoTenisMesa`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `torneoTenisMesa`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(64) NOT NULL,
  `apellido` VARCHAR(64) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `tipo` ENUM('Administrador', 'Jugador', 'Arbitro', 'Apostador') NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneoTenisMesa`.`Estructura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `torneoTenisMesa`.`Estructura` ;

CREATE TABLE IF NOT EXISTS `torneoTenisMesa`.`Estructura` (
  `idEstructura` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstructura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneoTenisMesa`.`Torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `torneoTenisMesa`.`Torneo` ;

CREATE TABLE IF NOT EXISTS `torneoTenisMesa`.`Torneo` (
  `idTorneo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idEstructura` INT NOT NULL,
  `cantidadJugadores` INT NOT NULL,
  `cantidadMesas` INT NULL,
  PRIMARY KEY (`idTorneo`),
  INDEX `fkEstructuraTorneo_idx` (`idEstructura` ASC),
  CONSTRAINT `fkEstructuraTorneo`
    FOREIGN KEY (`idEstructura`)
    REFERENCES `torneoTenisMesa`.`Estructura` (`idEstructura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneoTenisMesa`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `torneoTenisMesa`.`Partido` ;

CREATE TABLE IF NOT EXISTS `torneoTenisMesa`.`Partido` (
  `idPartido` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `idTorneo` INT NOT NULL,
  `idPartidoTorneo` INT NOT NULL,
  PRIMARY KEY (`idPartido`),
  INDEX `fkPartidoTorneo_idx` (`idTorneo` ASC),
  CONSTRAINT `fkPartidoTorneo`
    FOREIGN KEY (`idTorneo`)
    REFERENCES `torneoTenisMesa`.`Torneo` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneoTenisMesa`.`UsuarioPartido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `torneoTenisMesa`.`UsuarioPartido` ;

CREATE TABLE IF NOT EXISTS `torneoTenisMesa`.`UsuarioPartido` (
  `idPartido` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `resultado` INT NULL,
  PRIMARY KEY (`idPartido`, `idUsuario`),
  INDEX `fk_Partido_has_Usuario_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Partido_has_Usuario_Partido1_idx` (`idPartido` ASC),
  CONSTRAINT `fk_Partido_has_Usuario_Partido1`
    FOREIGN KEY (`idPartido`)
    REFERENCES `torneoTenisMesa`.`Partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_has_Usuario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `torneoTenisMesa`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `torneoTenisMesa`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `torneoTenisMesa`;
INSERT INTO `torneoTenisMesa`.`Usuario` (`idUsuario`, `nombre`, `apellido`, `cedula`, `estado`, `nombreUsuario`, `clave`, `tipo`, `telefono`) VALUES (1, 'admin', 'admin', '12345678', 1, 'admin', 'admin', 'Administrador', '864535');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
